[package]
name = "dronelab"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
openh264 = "0.9.0"
sdl2 = "0.38.0"
tello = "0.6.3"
tello-edu = "0.5.5"
tokio = { version = "1.47.1", features = ["full"] }
